apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-4b-fp8
  namespace: vllm-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-4b-fp8
  template:
    metadata:
      labels:
        app: qwen3-4b-fp8
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        eks.amazonaws.com/instance-family: r7i
      containers:
        - name: vllm
          image: public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          command: ["vllm", "serve"]
          args:
            - unsloth/Llama-3.2-3B-Instruct
            - --served-model-name=Llama-3.2-3B-Instruct
            - --max-model-len=32768
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: VLLM_LOGGING_LEVEL
              value: "DEBUG"
          resources:
            requests:
              cpu: 8
              memory: 16Gi
            limits:
              cpu: 8
              memory: 16Gi
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      tolerations:
        - key: cpu-llm
          value: "true"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-cpu-service
  namespace: vllm-inference
spec:
  selector:
    app: qwen3-4b-fp8
  ports:
    - name: http
      port: 8000