apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-4b-instruct-fp8
  namespace: vllm-inference
spec:
  replicas: 1  # Start with 1 replica, KEDA will manage scaling
  selector:
    matchLabels:
      app: qwen3-4b-instruct-fp8
  template:
    metadata:
      labels:
        app: qwen3-4b-instruct-fp8
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      nodeSelector:
        eks.amazonaws.com/instance-family: g6e
      containers:
        - name: vllm
          image: vllm/vllm-openai@sha256:0b51ec38fb965b44f6aa75d8d847c5f21bc062b7140e1d83444b39b67fc4a2ea
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          command: ["vllm", "serve"]
          args:
            - Qwen/Qwen3-4B-Instruct-2507-FP8
            - --served-model-name=qwen3-4b-instruct-fp8
            - --trust-remote-code
            - --gpu-memory-utilization=0.95
            - --max-model-len=32768
            - --disable-log-requests
            - --enable-auto-tool-choice
            - --tool-call-parser=hermes
            - --reasoning-parser=qwen3
          ports:
            - name: http
              containerPort: 8000
            - name: metrics
              containerPort: 8001
          env:
            - name: VLLM_PROMETHEUS_PORT
              value: "8001"
          resources:
            requests:
              cpu: 3.6
              memory: 29Gi
              nvidia.com/gpu: 1
            limits:
              cpu: 3.6
              memory: 29Gi
              nvidia.com/gpu: 1
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /secrets
            name: hf-secret-volume
            readOnly: true
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: hf-secret-volume
        secret:
          secretName: hf-secret
      tolerations:
        - key: nvidia.com/gpu
          value: "true"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: vllm-inference
  labels:
    app: qwen3-4b-instruct-fp8
spec:
  selector:
    app: qwen3-4b-instruct-fp8
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: metrics
      port: 8000
      targetPort: 8000