---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-notebooks
  namespace: jupyter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 500Gi
