apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-metrics
  namespace: vllm-inference
  labels:
    app: qwen3-4b-instruct-fp8
spec:
  selector:
    matchLabels:
      app: qwen3-4b-instruct-fp8
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scheme: http